### ISSUE TITLE
Bookings & Booking Period

### ISSUE THREAD

**Issue by RebeccaFlook** [Cetis/intelligent-campus#12]
I just wished to make a query regarding the storage of the bookings within the DataHub model for Intelligent Campus.  I have been working on how we would return a boolean value for whether at the current timestamp the room would be booked. This is quite a complicated query due to how the data is being stored currently.  From my understanding, for each room it involves checking for an exact date by getting the current timestamp, then if not looking at the booking period, reducing to the exact day, finding the current time period within those values and then scrolling through each string within that booking to find out if the booking is occurring on that week.  Peter and I had a discussion that for us, it would be easier if we could use logic on our side to sort the data on ingest to have two entries in ISO format that are the exact date with the start time and end time of the booking.  I'm sure there is a logical reason why it has been organised this way though so this can be discussed on the call this afternoon! Sorry for the lengthy description!

**Comment by scottbw** [comment]
The UDD model basically follows the structure used by the two most popular timetabling solutions used in HEPs. I'm guessing you're extracting room bookings from Exchange server?

An alternative is to pull all bookings out via CALDAV, or export to vCal format, and then extract the events.

If its querying the actual UDD model implemented in a data warehouse, locating an event should be pretty easy as its just a range query.

Hmm, maybe this would all be clearer on the call!

**Comment by scottbw** [comment]
We'll resolve this by "unrolling" a Booking into discrete Booking_Event entities that have absolute start datetime and end datetime to make matching easuer.

**Comment by alanepaull** [comment]
The booking entity contains mostly raw data from the timetabling system; or at least data that retains its scientia / celcat structure with single records that could contain recurring regular events. The new booking_event entity specifies unique events with absolute start and end datetimes.

This permits the linking of data as explained in the Use Case example at: https://github.com/Cetis/intelligent-campus/wiki/Use-Cases:-detailed-narrative-examples
