### ISSUE TITLE
Consider GeoJSON over OSM Way

### ISSUE THREAD

**Issue by ghost** [Cetis/intelligent-campus#5]
OSM Way is perhaps too OSM specific - not sure - but geoJSON is generic, easy to work with and doesn't require additional lookup.

For the dashboard we have maps showing for each class (nb. this will change in the dashboard for "users of campus" who are on campus so may not need to see where they are at a high level) and use either geoJSON Point or Polygon for all of the classes: Institution down to Device.

**Comment by ds10** [comment]
It would be good to talk about this, while it is a rough stab, the ontology was supposed to be an otology that was popular 'OSM keypair inspired' , but agnostic about being implemented in geoJSON or Open Street Map XML.

**Comment by ghost** [comment]
Not sure what you mean by 'OSM keypair inspired' but if it is 'agnostic about being implemented in geoJSON or Open Street Map XML' then we should be good to put something like a 'location' field with the geoJSON in?

**Comment by ds10** [comment]
Yes, that would be fine. 

The ontology is built on popular OSM tags. So it sugguests keypairs that go in the geoJSON  'properties' element, that would match up with popular OSM tags.

**Comment by ghost** [comment]
Great - thanks.

The other thing we might need which is related to the mapping is that sometimes a geo-related map isn't really what people need - rather they're looking for a simple abstraction of the building they are in. 

For this an SVG or similar is enough. I'm thinking we handle that outside of the data model maybe - that is have a SVG map API and the dashboard calls that with the site ID. Does that make sense?

**Comment by scottbw** [comment]
For the UDD, what we're reflecting here is that, certainly for University buildings (sites), these generally do exist in OSM but may not have any other geodata defined for them. So the OSM Way ID is a nice simple way to relate the data to OSM. If there is no OSM for a site or room, then you don't use it!

(The OSM IDs are used in a lot of third-party wayfinding applications, so its handy to have them. For example, Blindsquare is a wayfinding app used by blind and partially sighted students, and this uses OSM to generate directions.)

On the second point, in many universities the room code and site code will relate to an entity in facilities management systems like Archibus or Planone; these can also be used for map/plan renderings for buildings, which would tend to cover an SVG-type cases. So yes, that does make sense!
