### ISSUE TITLE
TTI Sensor Message

### ISSUE THREAD

**Issue by ghost** [Cetis/intelligent-campus#9]
When a ERS sensor is pushed through the Things Network with no decoding it looks like this:

`{
  "app_id": "jisc-fla-environment-sensors-1",
  "dev_id": "a81758fffe03469a",
  "hardware_serial": "A81758FFFE03469A",
  "port": 5,
  "counter": 27,
  "payload_raw": "AQDCAkEEAhoFAQcOBg==",
  "metadata": {
    "time": "2019-06-14T13:04:30.186408342Z",
    "frequency": 868.1,
    "modulation": "LORA",
    "data_rate": "SF7BW125",
    "coding_rate": "4/5",
    "gateways": [
      {
        "gtw_id": "eui-0080000000012c15",
        "timestamp": 3559704731,
        "time": "",
        "channel": 0,
        "rssi": -25,
        "snr": 9.5,
        "rf_chain": 0
      }
    ]
  },
  "downlink_url": "..."
}`

Couple of things to note:

* The message could have been recieved by more than one gateway and if you want to do geolocation using ToA or RSSI we need all the data for the gateways. We don't have gateway as part of a measurement. I can't see us needing it for analytics but wondered what you thought

* There is no "mac" but measurement needs one - just semantics really as  we can use hardware_serial instead - I'm happy for the field to stay as mac but again wondered what you thought.

**Comment by scottbw** [comment]
MAC does seem a bit prescriptive - maybe change it in the spec to "hardware_identifier" and apply a bit of 'duck typing' in the implementation to see if its an actual MAC address or a serial number?

**Comment by alanepaull** [comment]
Agreed that the provider needs to supply the sensor location somehow, by deriving it from available data.

**Comment by alanepaull** [comment]
sensor.mac changed to sensor.hardware_identifier as agreed.
